### ISSUE TITLE
Laravel 9 update?

### ISSUE THREAD

**Issue by rbruhn** [czim/laravel-paperclip#70] opened 2022-03-26 18:39 UTC
Updated to Laravel 9 but this package seems to be causing issues.
I updated everything except this package, commented out all the places I use this package in my models, and successfully updated everything else to Laravel 9.

Laravel 9
PHP 8.1

```
Problem 1
    - czim/file-handling[2.0.0, ..., 2.0.3] require psr/container ^1.0 -> found psr/container[1.0.0, ..., 1.x-dev] but the package is fixed to 2.0.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - czim/laravel-paperclip 4.0.0 requires czim/file-handling ^2.0 -> satisfiable by czim/file-handling[2.0.0, 2.0.1, 2.0.2, 2.0.3].
    - Root composer.json requires czim/laravel-paperclip ^4.0 -> satisfiable by czim/laravel-paperclip[4.0.0].

```

I see there is a pull request for file-handling: https://github.com/czim/file-handling/pull/11
Would that solve the issue?

**Comment by czim** [comment] 2022-03-27 11:16
That would partially solve it, but it looks like `psr/container` is also bumped a major version. I'd have to take some time to test it and release a new major version for the file handler.

**Comment by czim** [comment] 2022-03-27 19:21
`czim/file-handling` is updated to `2.1.0`, can you confirm that it installs for you now?

**Comment by Cibsmart** [comment] 2022-03-27 20:55
@czim I have confirmed, it now installs but getting the following error during package discovery:

`Declaration of Czim\FileHandling\Support\Container\LaravelContainerDecorator::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool`

Raised a PR to resolve this https://github.com/czim/file-handling/pull/12

**Comment by czim** [comment] 2022-03-27 21:05
Ah yes, my bad. I don't have much time or I'd be testing this myself, sorry.

I have bumped version `2.1.1` with the merged PR.

**Comment by rbruhn** [comment] 2022-03-27 23:19
Working for me. Thanks.

**Closed** 2022-03-28 08:50 UTC
